[build]
  command = "npm run build"
  publish="dist"
  # The base directory should be the path to the nested Vue project

  [[redirects]]
  from = "/https://getimage.netlify.app/api.unsplash.com/*"
  to = "/https://api.unsplash.com"
  status = 200